services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.pgvector
    environment:
      POSTGRES_DB: imagedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  web:
    build: .
    command: flask run --host=0.0.0.0 --port=8000 --debug
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:password123@db:5432/imagedb

volumes:
  postgres_data:
