FROM postgres:15

RUN apt-get update && \
    apt-get install -y postgresql-server-dev-15 git make gcc && \
    git clone --branch v0.4.2 https://github.com/pgvector/pgvector.git /pgvector && \
    cd /pgvector && make && make install && \
    rm -rf /pgvector && \
    apt-get remove -y postgresql-server-dev-15 git make gcc && \
    apt-get autoremove -y && apt-get clean
